// <auto-generated />
namespace EFDemo_CodeBasedMigrations.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Blog_Author : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Blog_Author));
        
        string IMigrationMetadata.Id
        {
            get { return "201807201803438_Blog_Author"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
